-- 部品進捗システム（仮称）DBスキーマ v0.1
-- 設計仕様書 1章準拠。テーブルは用途で3群に分ける。
--   ①取込テーブル      = 毎回洗い替え
--   ②算出結果テーブル  = バッチで再生成
--   ③アプリ固有テーブル = 画面から書込み・永続（取込で消えない）
-- ①②のキーは製造インスタンス単位の os_id。③も os_id に紐付ける。

-- ========== ① 取込テーブル（洗い替え） ==========
CREATE TABLE IF NOT EXISTS t_part (
  os_id         text PRIMARY KEY,
  part_no       text,
  part_name     text,
  category      text,
  kishu         text,   -- 機種(型式)。担当チームを分ける主キー
  final_due     date,
  pbs_due       date,   -- PBS計画納期(月末)。再計算でDUE_SOURCE切替を再現するため保持
  urgent_flag   boolean NOT NULL DEFAULT false,
  shortage_flag boolean NOT NULL DEFAULT false
);
ALTER TABLE t_part ADD COLUMN IF NOT EXISTS kishu text;    -- 既存DBのマイグレーション
ALTER TABLE t_part ADD COLUMN IF NOT EXISTS pbs_due date;  -- 既存DBのマイグレーション

-- OCTPuS由来のShop名フォールバック（SHOPごとの最頻手順内容）のキャッシュ。
-- 取込時に生成し、再計算(CSVを読まない)での名称解決に使う。取込で洗い替え。
CREATE TABLE IF NOT EXISTS t_shop_name (
  shop text PRIMARY KEY,
  name text
);

CREATE TABLE IF NOT EXISTS t_routing (
  os_id           text NOT NULL,
  seq             integer NOT NULL,       -- 工程順（昇順に採番し直した連番）
  seq_label       text,                   -- 元の工程NO（例 071-3）
  shop            text,
  job             text,
  plan_start      timestamptz,            -- JIW(計算)
  plan_end        timestamptz,            -- JND(計算)
  wip_flag        boolean NOT NULL DEFAULT false,  -- 仕掛=1（現在位置）
  material_status text,                   -- 払出状況
  out_date        date,                   -- 外注持出日
  in_date         date,                   -- 外注持込日
  eta_date        date,                   -- 納入予定日（外注の納期回答）
  order_no        text,                   -- 注文番号（外注PO）
  PRIMARY KEY (os_id, seq)
);

CREATE TABLE IF NOT EXISTS t_shop_master (
  shop    text NOT NULL,
  job     text NOT NULL,
  name    text,
  machine text,
  PRIMARY KEY (shop, job)
);

-- ========== ② 算出結果テーブル（バッチ再生成） ==========
CREATE TABLE IF NOT EXISTS t_part_status (
  os_id         text PRIMARY KEY,
  part_no       text,
  part_name     text,
  category      text,
  kishu         text,   -- 機種(型式)。担当チームを分ける主キー
  final_due     date,
  total_shops   integer,
  done_shops    integer,
  remain_shops  integer,
  current_shop  text,
  days_left     integer,
  buffer        integer,
  color         text,   -- red / yellow / green
  stagnant_days integer,
  urgent        boolean,
  shortage      boolean,
  computed_at   timestamptz
);
ALTER TABLE t_part_status ADD COLUMN IF NOT EXISTS kishu text;  -- 既存DBのマイグレーション

CREATE TABLE IF NOT EXISTS t_timeline (
  os_id       text NOT NULL,
  seq         integer NOT NULL,       -- Shopコマの連番（連続同一SHOPは圧縮済み）
  shop        text,
  name        text,
  status      text,   -- done / current / wait
  plan_end    date,
  is_milestone boolean NOT NULL DEFAULT false,
  ms_passed   boolean,
  ms_color    text,   -- 未通過マイルストンの色 red/yellow/green
  ms_due      date,
  gaic        boolean NOT NULL DEFAULT false,   -- 外注区間か
  gaic_status text,   -- blue/yellow/red
  order_no    text,
  PRIMARY KEY (os_id, seq)
);

-- ========== ③ アプリ固有テーブル（画面から書込・永続。取込で消さない） ==========
CREATE TABLE IF NOT EXISTS t_assignment (
  os_id       text PRIMARY KEY,
  owner       text NOT NULL DEFAULT '未割当',
  assigned_at timestamptz
);

CREATE TABLE IF NOT EXISTS t_trouble (
  os_id      text PRIMARY KEY,
  flagged    boolean NOT NULL DEFAULT false,
  flagged_at timestamptz,
  memo       text            -- 困りごとメモ（一覧非表示・詳細/ポップアップのみ）
);

CREATE TABLE IF NOT EXISTS t_note (
  os_id      text PRIMARY KEY,
  body       text,            -- 対応メモ
  updated_at timestamptz
);

-- ========== マスタ（運用側で保守する参照・設定系。設計仕様書3章） ==========
-- 取込(①)で消えない。算出ロジックの挙動を規定する。既定値はシードで現状挙動を再現。

-- 担当者マスタ m_owner（画面編集）
CREATE TABLE IF NOT EXISTS m_owner (
  owner_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL,
  dept       text,            -- 所属
  team       text,            -- 担当チーム（m_kishu.team と突合。自動割当で機種→人を解決）
  ad_account text,            -- ADアカウント
  role       text NOT NULL DEFAULT '工程員',  -- 工程員 / 管理者
  active     boolean NOT NULL DEFAULT true
);
-- 既存DB（旧m_owner）へのマイグレーション
ALTER TABLE m_owner ADD COLUMN IF NOT EXISTS dept text;
ALTER TABLE m_owner ADD COLUMN IF NOT EXISTS team text;
ALTER TABLE m_owner ADD COLUMN IF NOT EXISTS ad_account text;
ALTER TABLE m_owner ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT '工程員';

-- パラメータ設定 m_param（画面編集）: 2.7の外出し値
CREATE TABLE IF NOT EXISTS m_param (
  key        text PRIMARY KEY,
  value      text NOT NULL,
  description text
);

-- 中間マイルストン定義 m_milestone（画面編集）: どの工程を検査マイルストンにするか
--   match_type: shop(完全一致) / shop_prefix(前方一致) / name_contains(名称部分一致)
CREATE TABLE IF NOT EXISTS m_milestone (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_type text NOT NULL,
  pattern    text NOT NULL,
  label      text,            -- マイルストン名（任意）
  active     boolean NOT NULL DEFAULT true
);

-- Shop別標準LTマスタ m_shop_lt（初期Excel取込→UI化）: 未登録Shopは既定LTを使用
CREATE TABLE IF NOT EXISTS m_shop_lt (
  shop     text PRIMARY KEY,
  lt_days  numeric NOT NULL,
  active   boolean NOT NULL DEFAULT true
);

-- 稼働日カレンダー m_calendar（Excel取込/自動生成）: 休日を登録すると残日数を稼働日ベースに
CREATE TABLE IF NOT EXISTS m_calendar (
  cal_date   date PRIMARY KEY,
  is_workday boolean NOT NULL DEFAULT false, -- 既定は休日として登録（稼働日に穴を開ける）
  note       text
);

-- 外注先マスタ m_vendor（Excel取込）: 注文番号プレフィックス→外注先名/標準戻りLT
CREATE TABLE IF NOT EXISTS m_vendor (
  order_prefix text PRIMARY KEY,
  vendor_name  text NOT NULL,
  return_lt    numeric,
  active       boolean NOT NULL DEFAULT true
);

-- 完成品分類マスタ m_category（Excel取込）: 部品番号パターン→分類。priority昇順で最初の一致を採用
CREATE TABLE IF NOT EXISTS m_category (
  id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pattern  text NOT NULL,     -- 正規表現（部品番号に対して）
  category text NOT NULL,
  priority integer NOT NULL DEFAULT 100,
  active   boolean NOT NULL DEFAULT true
);

-- 機種→担当マスタ m_kishu（画面編集）: 機種(型式)ごとの担当チーム。
--   取込時に出現した機種を自動登録（担当は空）するので、運用は担当チームを埋めるだけ。
--   取込(①)では消さない＝ユーザーが割り当てた担当を温存する。
CREATE TABLE IF NOT EXISTS m_kishu (
  kishu  text PRIMARY KEY,
  team   text,             -- （将来用の予約列。現行は未使用）
  note   text,
  active boolean NOT NULL DEFAULT true
);

-- 担当者×機種の多対多（担当者マスタUIのチェックボックスで設定）。
-- 「チーム」という実体は持たず、同じ機種を担当する人が結果的に同グループになる。
-- 取込(①)では消さない＝担当割り当ての設定を温存する。
CREATE TABLE IF NOT EXISTS m_owner_kishu (
  owner_id integer NOT NULL,
  kishu    text NOT NULL,
  PRIMARY KEY (owner_id, kishu)
);

-- ========== 監査・ロール（設計仕様書1.3） ==========
CREATE TABLE IF NOT EXISTS t_audit_log (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app_user   text,
  action     text,            -- master.upsert / master.delete / assignment 等
  target     text,            -- 対象マスタ/テーブル名
  ref        text,            -- os_id や 主キー
  before     jsonb,
  after      jsonb,
  at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS t_user_role (
  app_user text PRIMARY KEY,
  role     text NOT NULL DEFAULT '工程員'  -- 工程員 / 管理者
);

CREATE INDEX IF NOT EXISTS idx_routing_osid ON t_routing(os_id);
CREATE INDEX IF NOT EXISTS idx_timeline_osid ON t_timeline(os_id);
CREATE INDEX IF NOT EXISTS idx_status_color ON t_part_status(color);
